server:
  port: 8887
spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/9kayer/BlogConfigServer.git
          search-paths:
            - 'config'
management:
  endpoints:
    enabled-by-default: true